version: '3'

services:
  database:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: nooksales
      POSTGRES_USER: nooksales
      POSTGRES_PASSWORD: nooksales
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: