import * as mongoose from 'mongoose';

export const CollectibleSchema = new mongoose.Schema({
    gameId: String,
    name: String,
    image: String,
    obtainedFrom: String,
    set: String,
    category: String,
    catchPhrase: String,
    house: String,
    model: String,
    museumPhrase: String,
    rarity: String,
    shadow: String,
    size: String,
    unlocksAfter: String,
    weather: String,
    uses: String,
    buy: Number,
    nookMiles: Number,
    number: Number,
    sell: Number,
    variant: Boolean,
    customize: Boolean,
    dIY: Boolean,
    reorder: Boolean,
    vFX: Boolean,
    variants: [String],
    activeMonthsNorth: [Number],
    activeMonthsSouth: [Number],
    activeTimes: [{ startTime: Number, endTime: Number }],
    materials: [{ count: Number, itemName: String }],
});